packages:
  - "studio"
  - "frontend"

strictDepBuilds: true
minimumReleaseAge: 1440
blockExoticSubdeps: true

patchedDependencies:
  sanity-plugin-media@5.0.11: patches/sanity-plugin-media@5.0.11.patch

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
